// api/spec/[channel].js  -  VERSION 2
// Campaign Spec Automation with optional campaign creation.
//
// Flow: monday label flips to "Design Approved" -> webhook -> this function
//   1. Pulls the order from monday
//   2. Generates the build spec with Claude (same as v1)
//   3. If STACKADAPT_WRITE_ENABLED=true: copies the reference campaign in
//      StackAdapt, applies the four edits, LEAVES IT PAUSED, and includes
//      the campaign link in the task update.
//      If DRY_RUN=true: does everything except execute mutations, and posts
//      the exact mutations it would have run, for human review.
//   4. Posts the result as an update on the monday item
//
// HARD RULES ENCODED BELOW - do not remove:
//   - This function NEVER activates, resumes, or unpauses a campaign.
//   - This function NEVER deletes or archives anything.
//   - Before creating, it checks for an existing campaign with the same
//     name and refuses to create a duplicate.
//
// Env vars (Vercel > Settings > Environment Variables, then Redeploy):
//   ANTHROPIC_API_KEY          required
//   MONDAY_API_TOKEN           required
//   STACKADAPT_API_KEY         required for write path (write-scoped key)
//   STACKADAPT_WRITE_ENABLED   "true" to enable the write path at all
//   DRY_RUN                    "true" = post mutations instead of running them
//
// Rollout: STACKADAPT_WRITE_ENABLED=true + DRY_RUN=true first. Read two or
// three dry-run posts, confirm them, then set DRY_RUN=false and redeploy.

const BOARD_ID = 6530567822;
const TRIGGER_LABEL = "Design Approved";

// VERIFIED column IDs - display names on this board are misleading.
const COLUMN_FOR_CHANNEL = {
  billboard: "dup__of_design1", // displayed as "Billboard"
  display: "dup__of_billboard", // displayed as "Digital Ads"
};

const REFERENCE = {
  display: { diamond: 3251039, fallback: 3324372 },
  billboard: { diamond: 3251037, fallback: 3324366 },
};

const CAMPAIGN_GROUPS = {
  // Verified group IDs. Extend as tiers are confirmed.
  diamond: 195699, // Diamond Luxury Orders
  opal: 195605, // Opal Luxury Orders
  "diamond black": 379913, // Diamond Black Luxury Orders
};

const SA_ENDPOINT = "https://api.stackadapt.com/graphql";

const recentlyProcessed = new Map();

export default async function handler(req, res) {
  if (req.body && req.body.challenge) {
    return res.status(200).json({ challenge: req.body.challenge });
  }

  const channel = req.query.channel;
  if (!COLUMN_FOR_CHANNEL[channel]) {
    return res.status(404).json({ error: "unknown channel route" });
  }
  const event = req.body?.event;
  if (!event || !event.pulseId) {
    return res.status(400).json({ error: "no event payload" });
  }
  if (event.columnId && event.columnId !== COLUMN_FOR_CHANNEL[channel]) {
    return res.status(200).json({ skipped: "column mismatch", got: event.columnId });
  }
  const newLabel = event.value?.label?.text || event.value?.label || "";
  if (newLabel && newLabel !== TRIGGER_LABEL) {
    return res.status(200).json({ skipped: "label is not Design Approved" });
  }

  const itemId = event.pulseId;
  const dedupeKey = `${itemId}:${channel}`;
  if (
    recentlyProcessed.has(dedupeKey) &&
    Date.now() - recentlyProcessed.get(dedupeKey) < 10 * 60 * 1000
  ) {
    return res.status(200).json({ skipped: "duplicate within 10 minutes" });
  }
  recentlyProcessed.set(dedupeKey, Date.now());

  try {
    const item = await fetchMondayItem(itemId);
    const tier = (item.values.label || "").toLowerCase().trim();
    const refId =
      REFERENCE[channel][tier] !== undefined
        ? REFERENCE[channel][tier]
        : tier === "diamond"
          ? REFERENCE[channel].diamond
          : REFERENCE[channel].fallback;

    const reference = await fetchReference(refId);

    const spec = await generateSpec(channel, item, reference, refId, tier);

    let buildReport = "";
    if (process.env.STACKADAPT_WRITE_ENABLED === "true") {
      buildReport = await buildCampaign({ channel, item, tier, refId });
    }

    const header =
      "SPEC GENERATED BY AUTOMATION v3 - verify before launch. " +
      "The campaign, if created below, is PAUSED and stays paused until a human activates it.\n\n";

    await postMondayUpdate(itemId, header + spec + (buildReport ? "\n\n" + buildReport : ""));
    return res.status(200).json({ ok: true, itemId, channel });
  } catch (err) {
    try {
      await postMondayUpdate(
        itemId,
        `AUTOMATION ERROR - ${channel} failed.\n${String(err).slice(0, 500)}\n` +
          `No campaign was activated. Check the draft state in StackAdapt if a build was in progress.`
      );
    } catch (_) {}
    console.error(err);
    return res.status(500).json({ error: String(err) });
  }
}

/* ------------------------- StackAdapt write path ------------------------- */

async function buildCampaign({ channel, item, tier, refId }) {
  const dryRun = process.env.DRY_RUN !== "false"; // default SAFE: dry run
  const streetAddress = item.name.split(",")[0].trim();
  const channelLabel = channel === "billboard" ? "Billboards" : "Digital Ads";
  const campaignName = `${streetAddress} - ${channelLabel}`;
  const log = [];
  const planned = [];

  // 1. Idempotency: refuse to create a duplicate.
  const existing = await saQuery(
    `query ($name: String!) {
      campaigns(filterBy: { name: $name }, first: 5) {
        nodes { id name state }
      }
    }`,
    { name: campaignName }
  ).catch(() => null);
  const match = existing?.campaigns?.nodes?.find((c) => c.name === campaignName);
  if (match) {
    return (
      `CAMPAIGN ALREADY EXISTS - nothing was created.\n` +
      `${match.name} (ID ${match.id}, state ${match.state}).\n` +
      `If a rebuild is intended, rename or archive the existing campaign by hand first.`
    );
  }

  // 2. Copy the reference. Mutation name discovered at runtime because the
  //    public schema has shifted between copyCampaign and duplicateCampaign.
  const copyMutationName = await discoverMutation(["copyCampaign", "duplicateCampaign"]);
  if (!copyMutationName) {
    return (
      "WRITE PATH UNAVAILABLE - the API key does not expose a campaign copy " +
      "mutation. The spec above is complete; build by hand. " +
      "Check the key's scopes include campaign write."
    );
  }

  const copyMutation = `mutation ($id: ID!) {
    ${copyMutationName}(input: { campaignId: $id }) {
      campaign { id name state }
      userErrors { message path }
    }
  }`;

  // 3. The four edits, applied to the copy.
  const flightStart = todayISO();
  const flightEnd = addDaysISO(30);
  const groupId = CAMPAIGN_GROUPS[tier];
  const updateInput = {
    name: campaignName,
    startTime: flightStart,
    endTime: flightEnd,
    ...(groupId ? { campaignGroupId: groupId } : {}),
    state: "PAUSED", // belt and suspenders; copies land paused anyway
  };
  const updateMutation = `mutation ($id: ID!, $input: CampaignUpdateInput!) {
    updateCampaign(input: { campaignId: $id, patch: $input }) {
      campaign { id name }
      userErrors { message path }
    }
  }`;

  if (dryRun) {
    planned.push(`WOULD RUN: ${copyMutationName} on reference ${refId}`);
    planned.push(`WOULD RUN: updateCampaign with ${JSON.stringify(updateInput)}`);
    planned.push(
      channel === "billboard"
        ? "WOULD LEAVE: geo for county cluster upload by hand (xlsx path), audience empty as inherited"
        : "WOULD FLAG: audience strip (four CTV segments, four or five interest segments) - " +
          "apply by hand until the strip mutation is verified"
    );
    return (
      "DRY RUN - no mutations were executed. Review the plan below, then set " +
      "DRY_RUN=false in Vercel and redeploy to arm the write path.\n\n" +
      planned.join("\n")
    );
  }

  // LIVE PATH
  const copied = await saQuery(copyMutation, { id: String(refId) });
  const copyResult = copied[copyMutationName];
  throwOnUserErrors(copyResult, "copy");
  const newId = copyResult.campaign.id;
  log.push(`Copied reference ${refId} -> new campaign ${newId}`);

  const updated = await saQuery(updateMutation, { id: String(newId), input: updateInput });
  throwOnUserErrors(updated.updateCampaign, "update");
  log.push(`Renamed to "${campaignName}", flight ${flightStart} to ${flightEnd}, group ${groupId || "unchanged"}, state PAUSED`);

  return (
    `CAMPAIGN CREATED, PAUSED - ID ${newId}\n` +
    log.join("\n") +
    `\n\nREMAINING BY HAND before activation:\n` +
    (channel === "billboard"
      ? `1. Upload the county geo xlsx (cluster in the spec above)\n2. Upload creative from the Air link\n3. QA against reference ${refId}\n4. Activate`
      : `1. Set display geography per the spec above\n2. Strip the audience segments listed in the spec\n3. Upload the ten creative sizes\n4. QA against reference ${refId}\n5. Activate`) +
    `\n\nThis automation never activates campaigns. That click is yours.`
  );
}

async function discoverMutation(candidates) {
  try {
    const data = await saQuery(
      `query { __schema { mutationType { fields { name } } } }`,
      {}
    );
    const names = new Set(data.__schema.mutationType.fields.map((f) => f.name));
    return candidates.find((c) => names.has(c)) || null;
  } catch {
    return null;
  }
}

function throwOnUserErrors(result, step) {
  if (result?.userErrors?.length) {
    throw new Error(`StackAdapt ${step}: ` + JSON.stringify(result.userErrors));
  }
  if (!result?.campaign) {
    throw new Error(`StackAdapt ${step}: no campaign in response`);
  }
}

async function saQuery(query, variables) {
  const r = await fetch(SA_ENDPOINT, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${process.env.STACKADAPT_API_KEY}`,
    },
    body: JSON.stringify({ query, variables }),
  });
  const j = await r.json();
  if (j.errors) throw new Error(JSON.stringify(j.errors));
  return j.data;
}

async function fetchReference(refId) {
  // Discover which fields the schema actually exposes on Campaign, then
  // query only those. Avoids hard errors from guessed field names.
  const wanted = [
    "name", "budget", "budgetType", "bidAmount", "bidAmountTotal",
    "startTime", "endTime", "state", "channel", "type",
  ];
  let fields = ["name"]; // guaranteed minimum
  try {
    const introspected = await saQuery(
      `query { __type(name: "Campaign") { fields { name } } }`,
      {}
    );
    const available = new Set(
      (introspected.__type?.fields || []).map((f) => f.name)
    );
    fields = wanted.filter((f) => available.has(f));
    if (!fields.length) fields = ["name"];
  } catch {
    /* introspection blocked; fall through with name only */
  }
  try {
    const data = await saQuery(
      `query ($id: ID!) { campaign(id: $id) { ${fields.join(" ")} } }`,
      { id: String(refId) }
    );
    return data.campaign || { warning: "reference not found" };
  } catch (e) {
    return { warning: "reference fetch failed: " + String(e).slice(0, 200) };
  }
}

function todayISO() {
  return new Date().toISOString().slice(0, 10);
}
function addDaysISO(d) {
  const t = new Date();
  t.setDate(t.getDate() + d);
  return t.toISOString().slice(0, 10);
}

/* ---------------------------- monday + Claude ---------------------------- */

async function fetchMondayItem(itemId) {
  const query = `query ($ids: [ID!]) {
    items(ids: $ids) { name column_values { id text } }
  }`;
  const r = await fetch("https://api.monday.com/v2", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: process.env.MONDAY_API_TOKEN,
    },
    body: JSON.stringify({ query, variables: { ids: [String(itemId)] } }),
  });
  const j = await r.json();
  if (j.errors) throw new Error("monday read: " + JSON.stringify(j.errors));
  const item = j.data.items[0];
  const values = {};
  for (const cv of item.column_values) values[cv.id] = cv.text;
  return { name: item.name, values };
}

async function postMondayUpdate(itemId, body) {
  const mutation = `mutation ($item: ID!, $body: String!) {
    create_update(item_id: $item, body: $body) { id }
  }`;
  const r = await fetch("https://api.monday.com/v2", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: process.env.MONDAY_API_TOKEN,
    },
    body: JSON.stringify({
      query: mutation,
      variables: { item: String(itemId), body: body.slice(0, 9000) },
    }),
  });
  const j = await r.json();
  if (j.errors) throw new Error("monday update: " + JSON.stringify(j.errors));
  return j.data.create_update.id;
}

async function generateSpec(channel, item, reference, refId, tier) {
  const userMessage = [
    `Channel: ${channel === "billboard" ? "Billboard (DOOH)" : "Digital Ads (Display)"}`,
    `Property: ${item.name}`,
    `Tier: ${item.values.label || "unknown"}`,
    `Agent: ${item.values.text03 || ""} (${item.values.email || ""})`,
    `Agent site: ${item.values.text_mkv75frc || ""}`,
    `List price field: ${item.values.numbers6 || ""}`,
    `Air asset link: ${item.values.link || ""}`,
    `Property page (click destination): ${item.values.dup__of_asset_link || ""}`,
    `Order deposit date: ${item.values.date0__1 || ""}`,
    ``,
    `Reference campaign to clone (ID ${refId}):`,
    JSON.stringify(reference, null, 2),
    ``,
    `Produce the ${channel} specification now.`,
  ].join("\n");

  const r = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": process.env.ANTHROPIC_API_KEY,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: "claude-sonnet-4-6",
      max_tokens: 2500,
      system: buildSystemPrompt(),
      messages: [{ role: "user", content: userMessage }],
    }),
  });
  const j = await r.json();
  if (j.error) throw new Error("anthropic: " + JSON.stringify(j.error));
  return j.content
    .filter((b) => b.type === "text")
    .map((b) => b.text)
    .join("\n");
}

function buildSystemPrompt() {
  return `You generate StackAdapt campaign build specifications for luxury real estate listings at LPT Realty and Aperture Global. You write one specification per request, for one channel, posted as a monday.com task update. Follow every rule below exactly.

CLONING. Campaigns are cloned from a reference, never built from scratch. Only these change per property: name, flight dates, geography, creative. Campaign group and budget change when the tier differs. Nothing else is touched: bid, budget type, goals, frequency, inventory, timezone, parting all ride along.

NAMING. Street address then channel. Example: 7119 Kinglet Court - Digital Ads. Street address only, not city, state, or zip.

FLIGHT. Thirty days, starting on or near today.

BUDGET. Display: 20,000 or 30,000 impressions at five dollar CPM, IMP type; 30,000 is the more common recent figure; state which you chose and why. Billboard: three hundred dollars at fifteen dollar CPM, COST type, fully consistent, no judgment needed.

DISPLAY GEOGRAPHY. Target the feeder market, where the buyer lives today, not where the house is. Designated market area is the default unit; drop to county when the market area is materially wider than the buyer pool. State the reasoning.

BILLBOARD GEOGRAPHY. A cluster of nine to thirteen counties covering the metro and its surrounding ring, DMA targeting off. List every county with its two letter state code, paste ready for the geographic upload spreadsheet, and note the geo xlsx is generated separately from the master template.

DISPLAY AUDIENCE. Must appear in full in every display spec, using ONLY the segment names written below. Never invent, substitute, or paraphrase a segment name. If a needed list is not written in these instructions, write "list not available in automation instructions, pull from reference campaign" instead of producing names.

STRIP, third party, all four contain the string Optimized for CTV:
1. 123Push > Optimized for CTV > Consumer > Financial Services > Investing > Interest > Real Estate
2. 123Push > Optimized for CTV > Consumer > Interest > Personal Finance > Real Estate
3. 123Push > Optimized for CTV > Consumer > Financial Services > Real Estate > Interest > Buying A Home
4. 123Push > Optimized for CTV > Consumer > Demographic > Financial > Investments > Real Estate

STRIP, interest: Smart Home / IoT. Home Remodeling / Home Renovation. Rent Your Home. Foreclosed Home Buyers and Flippers. First Time Home Buyers (present on the Diamond reference only).

KEEP, interest, exactly these eight: Home Buyers (ID 678). Vacation Homes Buyers. Home Buyers (ID 980, a second segment with the same name). Home Loans. Home Sellers. Second Time Home Buyers. Homeowners. Real Estate Agents and Realtors.

KEEP, third party, exactly these thirteen: 123Push Consumer Interest Personal Finance Real Estate. ShareThis US Life Event Home Buying. CoreLogic In Market HELOC Prospects Expiring Line. 123Push Consumer Demographic Financial Investments Real Estate. TrueData Home Buyers. Eyeota Real Estate Intent Investors. Eyeota Real Estate Intent Buyers. Eyeota Global ShareThis Real Estate Listings. Eyeota Global ShareThis Real Estate. Gravy In Market Home Buyers with Annual Income Greater Than 250K. Eyeota Global Lifesight Real Estate Interest. Datasys ANH purchase intent buying and selling homes. Captify Media In Market Residential Purchases.

Income floor: keep 250k+ on high seven figure properties, recommend 150k or 200k on lower priced ones, and note the Gravy segment is income gated at 250k so the two decisions go together.

BILLBOARD AUDIENCE. Billboards carry no audience at all. Say so explicitly: every audience field stays empty.

CREATIVE. Display: ten standard sizes from the Air link, click destination is the property page link, never the agent site. Billboard: creative from the Air link.

FLAGS. If the tier is missing, the price field is ambiguous, a link is absent, or the reference data contains a warning, say so plainly at the top. Do not invent values for missing fields.

STYLE. No em dashes or en dashes, use periods and commas. Digits are fine in tables and budgets. Direct and specific. Format for a monday update: short headers, tight labeled lines, no markdown tables.`;
}
