/**
 * Bundles src/ into dist/panel.js as a single CLASSIC script.
 *
 *   node tools/build.mjs
 *
 * Why this exists: UXP's ES-module support is not something to bet a panel on —
 * in particular bare specifiers like `import photoshop from "photoshop"`. When
 * module loading fails, UXP renders the HTML and silently runs none of the
 * JavaScript, so the panel looks fine but every control is dead. A classic
 * script with require() is the path Adobe's own samples take and has no such
 * failure mode.
 *
 * The sources stay as ES modules so `test/ops.test.mjs` can import the pure math
 * directly in Node. This step flattens them into one scope, which is safe only
 * because every top-level name across src/ is unique — verified below, and the
 * build fails loudly if that ever stops being true.
 */

import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

// Dependency order. Leaves first; main.js last.
const ORDER = [
  "src/ops/percentile.js",
  "src/ops/luminance.js",
  "src/ops/blur.js",
  "src/ops/highpass.js",
  "src/ops/levels.js",
  "src/ops/sobel.js",
  "src/ops/normal.js",
  "src/ops/vectordisp.js",
  "src/ops/ao.js",
  "src/ops/shadow.js",
  "src/ops/highlight.js",
  "src/presets.js",
  "src/itemjson.js",
  "src/imaging.js",
  "src/export.js",
  "src/pipeline.js",
  "src/main.js",
];

// Host bindings are emitted once in the preamble; the per-file versions are
// stripped so flattening doesn't produce duplicate `const` declarations.
const STRIP_LINE = [
  /^import\s+photoshop\s+from\s+"photoshop";\s*$/,
  /^import\s+uxp\s+from\s+"uxp";\s*$/,
  /^import\s+.*\s+from\s+"\.[^"]*";\s*$/,   // relative imports: all one scope now
  /^const\s*\{[^}]*\}\s*=\s*photoshop;\s*$/,
  /^const\s+fs\s*=\s*uxp\.storage\.localFileSystem;\s*$/,
];

function preamble(buildId) {
  return `// GENERATED by tools/build.mjs — do not edit. Edit src/ and rebuild.
// Single classic script: UXP injects require() here, unlike in ES modules.
"use strict";
(function () {
// Content hash of src/. Shown in the panel so a stale bundle is obvious: if the
// id in the panel doesn't match \`node tools/build.mjs\` output, Photoshop is
// running old code and needs a reload.
const BUILD_ID = ${JSON.stringify(buildId)};

// Positive proof of life, set before anything else can fail. Without it a panel
// whose script died is indistinguishable from one that loaded fine, since a
// healthy panel simply shows no message.
try {
  const boot = document.getElementById("status");
  if (boot) { boot.textContent = "Loading… (build " + BUILD_ID + ")"; boot.className = "busy"; }
} catch (e) { /* nothing we can do this early */ }

const photoshop = require("photoshop");
const uxp = require("uxp");
const { app, core, action, imaging } = photoshop;
const fs = uxp.storage.localFileSystem;
`;
}

const POSTAMBLE = `
})();
`;

/** Collect top-level declaration names so we can prove there are no collisions. */
function topLevelNames(code) {
  const names = [];
  const re = /^(?:export\s+)?(?:async\s+)?(?:function|const|let|var|class)\s+([A-Za-z_$][\w$]*)/gm;
  let m;
  while ((m = re.exec(code))) names.push(m[1]);
  return names;
}

const seen = new Map();
const chunks = [];
let collisions = 0;

for (const rel of ORDER) {
  const raw = readFileSync(join(ROOT, rel), "utf8");

  const kept = raw
    .split("\n")
    .filter((line) => !STRIP_LINE.some((re) => re.test(line.trim())))
    .join("\n")
    // `export function foo` -> `function foo`, `export const X` -> `const X`
    .replace(/^export\s+/gm, "");

  for (const name of topLevelNames(raw)) {
    if (seen.has(name)) {
      console.error(`NAME COLLISION: "${name}" in ${rel} already declared in ${seen.get(name)}`);
      collisions++;
    } else {
      seen.set(name, rel);
    }
  }

  chunks.push(`\n// ---------- ${rel} ----------\n${kept.trim()}\n`);
}

if (collisions) {
  console.error(
    `\n${collisions} collision(s). Flattening into one scope requires unique top-level names — rename, then rebuild.`
  );
  process.exit(1);
}

// Hash the markup and manifest too, not just src/. A panel-only edit still has
// to be reloaded, and the id is how you tell whether Photoshop actually did.
const buildId = createHash("sha256")
  .update(
    [...ORDER, "index.html", "manifest.json"]
      .map((rel) => readFileSync(join(ROOT, rel), "utf8"))
      .join("\u0000")
  )
  .digest("hex")
  .slice(0, 8);

const bundle = preamble(buildId) + chunks.join("") + POSTAMBLE;

// Guard: nothing module-flavoured may survive into a classic script.
const leftovers = bundle
  .split("\n")
  .map((l, i) => [i + 1, l])
  .filter(([, l]) => /^\s*(import|export)\s/.test(l));
if (leftovers.length) {
  console.error("Module syntax survived the transform:");
  for (const [n, l] of leftovers) console.error(`  ${n}: ${l.trim()}`);
  process.exit(1);
}

mkdirSync(join(ROOT, "dist"), { recursive: true });
writeFileSync(join(ROOT, "dist", "panel.js"), bundle);
console.log(
  `wrote dist/panel.js — build ${buildId} — ${ORDER.length} modules, ` +
    `${bundle.split("\n").length} lines, ${seen.size} top-level names`
);
